2.11BSD patch 496: C compiler bugs, cpp runs out of memory, yacc
Subject: C compiler bugs, cpp runs out of memory, yacc
Index:	 src/lib/ccom/{c03,c11}.c src/lib/cpp/cpp.c src/usr.bin/yacc/{dextern,Makefile}

Description:
	1) Patch #490 fixed one bug in shifting of unsigned long but introduced
	   a new bug when the '>>' operator is used with unsigned long.

	   Typedefs declared multiple times cause an error.

	   const/volatile must be allowed on both sides of a basic type

	   'const/volatile' referenced by indirection in structs caused the
	   member to not be declared.

	2) Patch #495 moved the ANSI C macros ___DATE___ and ___TIME___
	   from cc to cpp.  ctime(3) causes cpp to run out of D space due to
	   tables used by the timezone handling.

	3) A yacc table is slightly undersized.  This is unrelated to the bugs
	   above but is included here to simplify installation of a future
	   update.

Repeat-By:
	1)
	   a) Recompile a kernel, notice that ARP (the function arpresolve())
	      is broken resulting in failure to communicate on the ethernet.
	      This results from '>>' in the macro ARPTAB_HASH being miscompiled.

	   b) Compile the following:

	       extern int foo;
	       extern int foo;
	       typedef int bar;
	       typedef int bar;

	       x.c:4: bar redeclared

	   c) Compile the following:

	       struct buggy { int foo; };
	       struct buggy const bee;

	        x.c:2: Type clash

	    d) Compile the following:

	       struct f { char *const *arg2; } bug;
	       x(){ register char *const *p; p = bug.arg2; }

	       x.c:3: arg2 undefined; func. x
	       x.c:3: Illegal structure ref
	       x.c:3: warning: mixed pointer assignment

	2) Compile a kernel.  Networking driver if_de.c is known to fail:

# cc -O -DKERNEL -DMASTER -DINET -I. -I../h -DSUPERVISOR -S ../pdpif/if_de.c
../pdpif/if_de.c:1048: error: xmalloc: out of mem

	3) A program ported to 2.11 required a slightly larger state table
	   in yacc.

Fix:
	1) ragge@tethuvudet.se:

	   "The logic in how I wrote it was correct, but I did make a
	    mistake...  I set nreg to 2 to tell there are only two
	    registers available...  But - when looking deeper into this
	    it seems that c1 subtracts one from the value ... (which I missed)."

	   "Allow for typedefs to be declared multiple times (in the same way as
	    extern).  This is a nice addition in c11 that can simplify headers
	    significantly (no need for protection).

	   "const/volatile must be allowed on both sides of a basic type but got
	    an error if the type was a struct."

	2) My suggestion was to call the external ctime() functions in
	   /usr/libexec/ctimed.

	   ragge@tethuvudet.se:

	    "- Only call ctime() when __TIME__ or __DATE__ are referenced.
	     - Lower vmf pages to 12.

	     I noticed that the memory use was quite close to max when
	     testing, so decreasing the number of vmf pages seemed reasonable.

             I also noticed that expanding the mbuf macros required many
	     expansion buffers. I will revisit this sometimes."

	3) The increase in MEMSIZE is offset by implementing shared strings
	   using xstr(1)

	Cut where indicated and save to a file (/tmp/496.patch).  Then:

cd /
patch -p0 < /tmp/496.patch

cd /usr/src/lib/cpp
make install
make clean

cd ../ccom
make install
make clean

cd /usr/src/usr.bin/yacc
make install
make clean

	This and previous updates to 2.11BSD are available at the following
	locations:

	ftp://ftp.dfupdate.se/pub/pdp11/2.11BSD
	https://www.tuhs.org/Archive/Distributions/UCB/2.11BSD/Patches/
	ftp://ftp.2bsd.com/2.11BSD
	http://www.2bsd.com/2.11BSD/

Source: https://www.tuhs.org/Archive/Distributions/UCB/2BSD/2.11BSD/Patches/496

Co-Authored-By: Claude Opus 5.5 <noreply@anthropic.com>
Claude-Session: https://claude.ai/code/session_01Vb1qstb69mh3NKDCWZ2NBD